import{i as g,a as E}from"./assets/vendor-22aaac4a.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v=document.getElementById("searchInput");document.getElementById("searchButton");const h=document.getElementById("imageContainer"),p=document.getElementById("loadingIndicator"),d=document.getElementById("loadMoreButton"),w=document.getElementById("searchForm"),I=document.getElementById("endOfResultsMessage");document.addEventListener("DOMContentLoaded",async function(){const f="42207002-bb01baf83cbb3b924a651843b";let o=1,a="",i=0;w.addEventListener("submit",async t=>{t.preventDefault();const n=v.value.trim();if(n){a=n,o=1,r();try{await y(a,o),m()}catch(c){console.error("Error occurred during search:",c)}finally{s()}}else g.error({title:"Error",message:"Please enter a search term."})}),d.addEventListener("click",async()=>{o++,r();try{await y(a,o),m()}catch(t){console.error("Error occurred during search:",t)}finally{s()}});function e(t){u();const n=t.map(c=>b(c)).join("");h.innerHTML+=n,lightbox.refresh()}function r(){p.style.display="block"}function s(){p.style.display="none"}async function y(t,n){const c=`https://pixabay.com/api/?key=${f}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=15`;try{const l=(await E.get(c)).data;l.hits&&l.hits.length>0?(i=l.totalHits,n===1&&u(),e(l.hits),m()):n===1?(g.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again."}),u()):d.style.display="none"}catch{throw g.error({title:"Error",message:"An error occurred while fetching images. Please try again."}),new Error("An error occurred while fetching images. Please try again.")}}function b(t){return`
          <div class="image-card">
              <a href="${t.largeImageURL}" class="card-link" data-lightbox="image">
                  <img src="${t.webformatURL}" alt="${t.tags}" class="card-image">
              </a>
              <div class="card-details">
                  <p class="card-text"><strong>Likes:</strong> ${t.likes}</p>
                  <p class="card-text"><strong>Views:</strong> ${t.views}</p>
              </div>
              <div class="card-details">
                  <p class="card-text"><strong>Comments:</strong> ${t.comments}</p>
                  <p class="card-text"><strong>Downloads:</strong> ${t.downloads}</p>
              </div>
          </div>
      `}function u(){h.innerHTML=""}function m(){i>o*40?(d.style.display="block",I.textContent=""):(d.style.display="none",I.textContent="We're sorry, but you've reached the end of search results.")}});
//# sourceMappingURL=commonHelpers.js.map
